run:
  timeout: 1m
  skip-dirs:
    - scripts
    - internal/testcode/.*_gen

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - asciicheck
    - errorlint
    - depguard
    - makezero
    - predeclared
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec


# output configuration options
output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

linters-settings:

  depguard:
    list-type: denylist
    packages:
      - github.com/aws/aws-sdk-go/aws
    packages-with-error-message:
      - github.com/aws/aws-sdk-go/aws: 'use v2 sdk instead'

  gocritic:
    disabled-checks:
      - newDeref # it's wrong on generics
      - elseif
      - singleCaseSwitch

  govet:
    check-shadowing: true
    # enable-all: true