package awseventgenerator

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"sort"
	"strings"
)

const (
	skipCodeGen = false
)

func getOrderedFieldNames(m map[string]Field) []string {
	keys := make([]string, len(m))
	idx := 0
	for k := range m {
		keys[idx] = k
		idx++
	}
	sort.Strings(keys)
	return keys
}

func collectTopLevelStruct(structs map[string]Struct) map[string]Struct {
	m := make(map[string]Struct)

	for sk, s := range structs {
		m[sk] = s
	}

	for _, s := range structs {
		for _, f := range s.Fields {
			sname := strings.Trim(f.Type, "[]*")
			if _, ok := m[sname]; ok {
				delete(m, sname)
			}
		}
	}
	return m
}

func getOrderedStructNames(m map[string]Struct) []string {
	keys := make([]string, len(m))
	idx := 0
	for k := range m {
		keys[idx] = k
		idx++
	}
	sort.Strings(keys)
	return keys
}

// Output generates code and writes to w.
func Output(w io.Writer, g *Generator) error {

	var outputBuf bytes.Buffer

	structs := g.Structs
	aliases := g.Aliases

	var pkg string

	switch pVal := g.config.PackageName.(type) {
	case string:
		pkg = pVal
	case PackageNameFunc:
		pkg = pVal(g.schemas[0])
	default:
		return fmt.Errorf("invalid PackageName config value: %T %v", pVal, pVal)
	}

	fmt.Fprintln(&outputBuf, "// Code generated by awseventgenerator. DO NOT EDIT.")
	fmt.Fprintln(&outputBuf)
	fmt.Fprintf(&outputBuf, "package %v\n", cleanPackageName(pkg))

	// write all the code into a buffer, compiler functions will return list of imports
	// write list of imports into main output stream, followed by the code
	codeBuf := new(bytes.Buffer)
	imports := make(map[string]bool)

	topLevel := collectTopLevelStruct(structs)
	_ = topLevel

	for _, k := range getOrderedStructNames(structs) {
		s := structs[k]
		if !skipCodeGen {
			if s.GenerateCode {
				emitMarshalCode(codeBuf, s, imports)
				emitUnmarshalCode(codeBuf, s, imports)
			}
		} else {
			imports["encoding/json"] = true
		}
		for _, str := range s.importTypes {
			imports[str] = true
		}
	}

	if len(imports) > 0 {
		fmt.Fprintf(&outputBuf, "\nimport (\n")
		for k := range imports {
			fmt.Fprintf(&outputBuf, "    \"%s\"\n", k)
		}
		fmt.Fprintf(&outputBuf, ")\n")
	}

	if len(g.Constants) > 0 {
		fmt.Fprintf(&outputBuf, "\nconst (\n")
		for k, vraw := range g.Constants {
			fmt.Fprintf(&outputBuf, "  %s = ", k)
			switch v := vraw.(type) {
			case int, float64:
				fmt.Fprintf(&outputBuf, "%v\n", v)
			case bool:
				fmt.Fprintf(&outputBuf, "%t\n", v)
			default:
				fmt.Fprintf(&outputBuf, "`%v`\n", v)
			}
		}
		fmt.Fprintf(&outputBuf, ")\n")
	}

	for _, k := range getOrderedFieldNames(aliases) {
		a := aliases[k]

		fmt.Fprintln(&outputBuf, "")
		// fmt.Fprintf(&outputBuf, "// %s\n", a.Name)
		fmt.Fprintf(&outputBuf, "type %s = %s\n", a.Name, a.Type)
	}

	for _, k := range getOrderedStructNames(structs) {
		s := structs[k]

		fmt.Fprintln(&outputBuf, "")
		outputNameAndDescriptionComment(s.Name, s.Description, &outputBuf)

		if len(s.Fields) == 0 {
			fmt.Fprintf(&outputBuf, "type %s = map[string]interface{}\n", s.Name)
			continue
		}

		fmt.Fprintf(&outputBuf, "type %s struct {\n", s.Name)

		for _, fieldKey := range getOrderedFieldNames(s.Fields) {
			f := s.Fields[fieldKey]

			// Only apply omitempty if the field is not required.
			omitempty := ",omitempty"
			if f.Required {
				omitempty = ""
			}

			if f.Description != "" {
				outputFieldDescriptionComment(f.Description, &outputBuf)
			}

			if len(f.EnumValues) > 0 {
				fmt.Fprintf(&outputBuf, "\n  // Values: %s\n", strings.Join(f.EnumValues, ", "))
			}

			jsonName := f.JSONName
			ftype := f.Type
			if ftype == "int" {
				ftype = "int64"
			} else if ftype == "string" && f.Format == "date-time" {
				ftype = "time.Time"
			}

			nonPointerFtype := strings.TrimPrefix(ftype, "*")

			if ftype != "interface{}" && !strings.HasPrefix(ftype, "[]") && !strings.HasPrefix(ftype, "*") {
				ftype = "*" + ftype
			}

			if aType, ok := g.Aliases[nonPointerFtype]; ok && strings.HasPrefix(aType.Type, "map") {
				ftype = nonPointerFtype
			}

			if strings.HasPrefix(ftype, "*map") {
				ftype = strings.TrimPrefix(ftype, "*")
			}

			if f.Format == "raw" {
				ftype = "json.RawMessage"
			}
			fmt.Fprintf(&outputBuf, "  %s %s `json:\"%s%s\"`\n", f.Name, ftype, jsonName, omitempty)

			// fmt.Fprintf(&outputBuf, "  %s %s `json:\"%s%s\"`\n", f.Name, f.Type, f.JSONName, omitempty)
		}

		fmt.Fprintln(&outputBuf, "}")
	}

	// write code after structs for clarity
	outputBuf.Write(codeBuf.Bytes())

	if g.config.NoFormatCode {
		_, err := outputBuf.WriteTo(w)
		return err

	} else {

		formattedBytes, err := format.Source(outputBuf.Bytes())
		if err != nil {
			return err
		}

		_, err = w.Write(formattedBytes)
		return err
	}
}

func emitEnum(w io.Writer, enum Enum) error {

	return nil
}

func emitMarshalCode(w io.Writer, s Struct, imports map[string]bool) {
	imports["bytes"] = true
	fmt.Fprintf(w,
		`
func (strct *%s) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
`, s.Name)

	if len(s.Fields) > 0 {
		fmt.Fprintf(w, "    comma := false\n")
		// Marshal all the defined fields
		for _, fieldKey := range getOrderedFieldNames(s.Fields) {
			f := s.Fields[fieldKey]
			if f.JSONName == "-" {
				continue
			}
			if f.Required {
				fmt.Fprintf(w, "    // \"%s\" field is required\n", f.Name)
				// currently only objects are supported
				if strings.HasPrefix(f.Type, "*") {
					imports["errors"] = true
					fmt.Fprintf(w, `    if strct.%s == nil {
        return nil, errors.New("%s is a required field")
    }
`, f.Name, f.JSONName)
				} else {
					fmt.Fprintf(w, "    // only required object types supported for marshal checking (for now)\n")
				}
			}

			fmt.Fprintf(w,
				`    // Marshal the "%[1]s" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"%[1]s\": ")
	if tmp, err := json.Marshal(strct.%[2]s); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
`, f.JSONName, f.Name)
		}
	}
	if s.AdditionalType != "" {
		if s.AdditionalType != "false" {
			imports["fmt"] = true

			if len(s.Fields) == 0 {
				fmt.Fprintf(w, "    comma := false\n")
			}

			fmt.Fprintf(w, "    // Marshal any additional Properties\n")
			// Marshal any additional Properties
			fmt.Fprintf(w, `    for k, v := range strct.AdditionalProperties {
		if comma {
			buf.WriteString(",")
		}
        buf.WriteString(fmt.Sprintf("\"%%s\":", k))
		if tmp, err := json.Marshal(v); err != nil {
			return nil, err
		} else {
			buf.Write(tmp)
		}
        comma = true
	}
`)
		}
	}

	fmt.Fprintf(w, `
	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}
`)
}

func emitUnmarshalCode(w io.Writer, s Struct, imports map[string]bool) {
	imports["encoding/json"] = true
	// unmarshal code
	fmt.Fprintf(w, `
func (strct *%s) UnmarshalJSON(b []byte) error {
`, s.Name)
	// setup required bools
	for _, fieldKey := range getOrderedFieldNames(s.Fields) {
		f := s.Fields[fieldKey]
		if f.Required {
			fmt.Fprintf(w, "    %sReceived := false\n", f.JSONName)
		}
	}
	// setup initial unmarshal
	fmt.Fprintf(w, `    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }`)

	// figure out if we need the "v" output of the range keyword
	needVal := "_"
	if len(s.Fields) > 0 || s.AdditionalType != "false" {
		needVal = "v"
	}
	// start the loop
	fmt.Fprintf(w, `
    // parse all the defined properties
    for k, %s := range jsonMap {
        switch k {
`, needVal)
	// handle defined properties
	for _, fieldKey := range getOrderedFieldNames(s.Fields) {
		f := s.Fields[fieldKey]
		if f.JSONName == "-" {
			continue
		}
		fmt.Fprintf(w, `        case "%s":
            if err := json.Unmarshal([]byte(v), &strct.%s); err != nil {
                return err
             }
`, f.JSONName, f.Name)
		if f.Required {
			fmt.Fprintf(w, "            %sReceived = true\n", f.JSONName)
		}
	}

	// handle additional property
	if s.AdditionalType != "" {
		cleanedAddtlType := strings.TrimPrefix(s.AdditionalType, "*")
		if s.AdditionalType == "false" {
			// all unknown properties are not allowed
			imports["fmt"] = true
			fmt.Fprintf(w, `        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
`)
		} else {
			fmt.Fprintf(w, `        default:
            // an additional "%s" value
            var additionalValue %s
            if err := json.Unmarshal([]byte(v), &additionalValue); err != nil {
                return err // invalid additionalProperty
            }
            if strct.AdditionalProperties == nil {
                strct.AdditionalProperties = make(map[string]%s, 0)
            }
            strct.AdditionalProperties[k]= additionalValue
`, cleanedAddtlType, cleanedAddtlType, cleanedAddtlType)
		}
	}
	fmt.Fprintf(w, "        }\n") // switch
	fmt.Fprintf(w, "    }\n")     // for

	// check all Required fields were received
	for _, fieldKey := range getOrderedFieldNames(s.Fields) {
		f := s.Fields[fieldKey]
		if f.Required {
			imports["errors"] = true
			fmt.Fprintf(w, `    // check if %s (a required property) was received
    if !%sReceived {
        return errors.New("\"%s\" is required but was not present")
    }
`, f.JSONName, f.JSONName, f.JSONName)
		}
	}

	fmt.Fprintf(w, "    return nil\n")
	fmt.Fprintf(w, "}\n") // UnmarshalJSON
}

func outputNameAndDescriptionComment(name, description string, w io.Writer) {
	if description == "" {
		return
	}

	if strings.Index(description, "\n") == -1 {
		fmt.Fprintf(w, "// %s\n", description)
		return
	}

	dl := strings.Split(description, "\n")
	fmt.Fprintf(w, "// %s\n", strings.Join(dl, "\n// "))
}

func outputFieldDescriptionComment(description string, w io.Writer) {
	if strings.Index(description, "\n") == -1 {
		fmt.Fprintf(w, "\n  // %s\n", description)
		return
	}

	dl := strings.Split(description, "\n")
	fmt.Fprintf(w, "\n  // %s\n", strings.Join(dl, "\n  // "))
}

func cleanPackageName(pkg string) string {
	pkg = strings.Replace(pkg, " ", "", -1)
	pkg = strings.Replace(pkg, ".", "", -1)
	pkg = strings.Replace(pkg, "-", "", -1)
	return pkg
}
