// Code generated by awseventgenerator/internal/generators/testcode. DO NOT EDIT.

package testsuitegenerated

import (
	"encoding/json"
	"github.com/stretchr/testify/require"
	"testing"
	"time"

	abandoned "github.com/webdestroya/awseventgenerator/internal/testcode/abandoned_gen"
)

func TestGenerated_abandoned(t *testing.T) {

	strVal := "someString"
	floatVal := float64(1232.1424)
	intVal := int64(1232)
	timeVal := time.Now().UTC()
	trueVal := true
	anyVal := struct {
		Thing string `json:"thinger"`
	}{Thing: "anywayanyday"}

	require.IsType(t, *new(string), strVal)
	require.IsType(t, *new(float64), floatVal)
	require.IsType(t, *new(int64), intVal)
	require.IsType(t, *new(time.Time), timeVal)
	require.IsType(t, *new(bool), trueVal)
	_ = anyVal

	t.Run("aliases", func(t *testing.T) {
		require.IsType(t, *new(interface{}), *new(abandoned.Abandoned))
	})

	t.Run("structs", func(t *testing.T) {
		t.Run("Root", func(t *testing.T) {
			genStruct := &abandoned.Root{
				Abandoned: anyVal,
				Name:      strVal,
			}
			t.Run("json", func(t *testing.T) {
				jsonOut, err := json.Marshal(genStruct)
				require.NoError(t, err)

				unmarObj := &abandoned.Root{}
				require.NoError(t, json.Unmarshal(jsonOut, unmarObj))

				jsonOut2, err := json.Marshal(unmarObj)
				require.NoError(t, err)
				require.JSONEq(t, string(jsonOut), string(jsonOut2))

				var jsearch interface{}
				require.NoError(t, json.Unmarshal(jsonOut, &jsearch))
				require.GreaterOrEqual(t, jmesMatch(t, jsearch, `length("abandoned")`).(float64), 1.0)
				requireJmesMatch(t, jsearch, `"name"`, strVal, "Name")

			})
			t.Run("fields", func(t *testing.T) {
				require.NotNil(t, genStruct.Abandoned) // Lazily Tested: abandoned.Root.Abandoned == Abandoned
				require.Equal(t, strVal, abandoned.Root{Name: strVal}.Name)
			})
		})

	})

}
