// Code generated by awseventgenerator/internal/generators/testcode. DO NOT EDIT.

package testsuitegenerated

import (
	"encoding/json"
	"github.com/stretchr/testify/require"
	"testing"
	"time"

	arrayofref "github.com/webdestroya/awseventgenerator/internal/testcode/arrayofref_gen"
)

func TestGenerated_arrayofref(t *testing.T) {

	strVal := "someString"
	floatVal := float64(1232.1424)
	intVal := int64(1232)
	timeVal := time.Now().UTC()
	trueVal := true
	anyVal := struct {
		Thing string `json:"thinger"`
	}{Thing: "anywayanyday"}

	require.IsType(t, *new(string), strVal)
	require.IsType(t, *new(float64), floatVal)
	require.IsType(t, *new(int64), intVal)
	require.IsType(t, *new(time.Time), timeVal)
	require.IsType(t, *new(bool), trueVal)
	_ = anyVal

	t.Run("aliases", func(t *testing.T) {
		require.IsType(t, *new([]arrayofref.Product), *new(arrayofref.Root))
	})

	t.Run("structs", func(t *testing.T) {
		t.Run("Product", func(t *testing.T) {
			genStruct := &arrayofref.Product{
				Id:    floatVal,
				Name:  strVal,
				Price: floatVal,
				Tags:  []string{strVal},
			}
			t.Run("json", func(t *testing.T) {
				jsonOut, err := json.Marshal(genStruct)
				require.NoError(t, err)

				unmarObj := &arrayofref.Product{}
				require.NoError(t, json.Unmarshal(jsonOut, unmarObj))

				jsonOut2, err := json.Marshal(unmarObj)
				require.NoError(t, err)
				require.JSONEq(t, string(jsonOut), string(jsonOut2))

				var jsearch interface{}
				require.NoError(t, json.Unmarshal(jsonOut, &jsearch))
				requireJmesMatch(t, jsearch, `"id"`, floatVal, "Id")
				requireJmesMatch(t, jsearch, `"name"`, strVal, "Name")
				requireJmesMatch(t, jsearch, `"price"`, floatVal, "Price")
				require.GreaterOrEqual(t, jmesMatch(t, jsearch, `length("tags")`).(float64), 1.0)

			})
			t.Run("fields", func(t *testing.T) {
				require.Equal(t, floatVal, arrayofref.Product{Id: floatVal}.Id)
				require.Equal(t, strVal, arrayofref.Product{Name: strVal}.Name)
				require.Equal(t, floatVal, arrayofref.Product{Price: floatVal}.Price)
				require.Contains(t, arrayofref.Product{Tags: []string{strVal}}.Tags, strVal)
			})
		})

	})

}
